Style/minimal design
HeleneAmouzou/QuiPayeQuoiHelene pull request #14
Opened 2023-05-03 09:38 UTC by HeleneAmouzou

2023-05-03 10:14 UTC, qroques requested changes

2023-05-03 10:14 UTC, qroques commented on apps/back/templates/home/index.html.twig
> +            <a href="{{ path('group_balance', {'groupId': 2}) }}" class="btn btn-primary btn-accueil btn-block">Afficher la balance</a>
pourquoi ces id en dur?

2023-05-03 10:14 UTC, qroques commented on apps/back/templates/group/displayBalance.html.twig
> +                            <td>{{ (memberBalance|round(0,'common'))|format_currency }}</td>
```suggestion
                            <td>{{ memberBalance|round(0,'common')|format_currency }}</td>
```

2023-05-03 10:14 UTC, qroques commented on apps/back/templates/base.html.twig
> +                    <p class="display-7 pt-2 mb-3">&copy; <span class="italic-text">Qui Paie Quoi ? </span> {{ "now" | date("Y") }} - Hélène Amouzou </p>
La date du copyright se met à jour automatiquement du coup?

2023-05-03 10:14 UTC, qroques commented on apps/back/templates/base.html.twig
> +        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
Tu pourrais avoir un lien vers le CDN de bootstrap directement. Cela fera que l'utilisateurs téléchargeront le CSS depuis leur serveur plutôt que celui qui sert l'application. C'est une optimisation mineure mais tout de meme

2023-05-03 10:14 UTC, qroques commented on apps/back/src/Form/ExpenseType.php
> +            // ])
Que s'est-il passé ici?

2023-05-03 10:14 UTC, qroques commented on apps/back/public/logos/logo-quipaiequoi-simple.png
Est ce un fond blanc ou transparent?

2023-05-03 11:48 UTC, HeleneAmouzou commented on apps/back/templates/home/index.html.twig
> +            <a href="{{ path('group_balance', {'groupId': 2}) }}" class="btn btn-primary btn-accueil btn-block">Afficher la balance</a>
Cela correspond à l'id du seul groupe existant, en attendant de pouvoir créer d'autres groupes

2023-05-03 11:51 UTC, HeleneAmouzou commented on apps/back/templates/base.html.twig
> +                    <p class="display-7 pt-2 mb-3">&copy; <span class="italic-text">Qui Paie Quoi ? </span> {{ "now" | date("Y") }} - Hélène Amouzou </p>
Exactement !

2023-05-03 11:52 UTC, qroques commented on apps/back/templates/home/index.html.twig
> +            <a href="{{ path('group_balance', {'groupId': 2}) }}" class="btn btn-primary btn-accueil btn-block">Afficher la balance</a>
Je suggererais d'ajouter une liste de tous les groupes existants et pour chacun d'eux, un lien vers la route `group_balance`

2023-05-03 12:04 UTC, NathanDid requested changes

2023-05-03 12:04 UTC, NathanDid commented on apps/back/public/css/style.css
> +    background-color: #041635 !important;
Il faut toujours éviter les `!important` en css

2023-05-03 12:10 UTC, HeleneAmouzou commented on apps/back/src/Form/ExpenseType.php
> +            // ])
Au départ le bouton de validation du formulaire était créé dans cette classe, finalement je l'ai rajouté directement dans le twig `add.html.twig`

2023-05-03 12:15 UTC, HeleneAmouzou commented on apps/back/public/logos/logo-quipaiequoi-simple.png
Ce n'est pas le bon logo, celui utilisé a un fond transparent, je le mets dans le prochain commit.

2023-05-03 12:15 UTC, qroques commented on apps/back/public/css/style.css
> +    background-color: #041635 !important;
Je dirais meme plus, il ne faut jamais les préférer :trollface:

2023-05-04 07:56 UTC, NathanDid requested changes

2023-05-04 07:56 UTC, NathanDid commented on apps/back/templates/base.html.twig
> +        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
C'était mieux avant ! Que se passera-t-il si le site distant ne répond plus ?

2023-05-04 12:08 UTC, NathanDid approved these changes

2023-05-05 08:51 UTC, qroques approved these changes

2023-05-05 08:52 UTC, merged