Feature/display balance
HeleneAmouzou/QuiPayeQuoiHelene pull request #9
Opened 2023-04-20 07:45 UTC by HeleneAmouzou

2023-04-20 07:59 UTC, KevinArtus commented on apps/back/src/Command/ViewBalanceCommand.php
> +        asort($groupBalance);
Is it necessary to sort this array ?

2023-04-20 08:04 UTC, AntoineLelaisant requested changes

2023-04-20 08:04 UTC, AntoineLelaisant commented on apps/back/src/Controller/ExpenseController.php
> +        }
```suggestion
        if ($group === null) {
            throw new HttpNotFoundException();
        }
        
        return $this->render('expense/list.html.twig', [
            'group' => $group,
        ]);
```

2023-04-20 08:04 UTC, AntoineLelaisant commented on apps/back/src/Controller/GroupController.php
> +        $application->run($input, $output);
I do not know if anyone suggest you to do this, but this is very (VERY) strange to create a new console `Application` in a Controller. Console Application are designed to be run in a CLI context and not through an HTTP call.

If you want to share some logic between your command and your controller, I think you should migrate this logic in a separated class. Then you could use this separated class in both your command and your controller.

2023-04-20 08:38 UTC, HeleneAmouzou commented on apps/back/src/Command/ViewBalanceCommand.php
> +        asort($groupBalance);
I did it because I wanted the `$memberBalance` to display in ascending order. Should I do it in another class than the command ?

2023-04-20 08:48 UTC, clementvtrd commented on apps/back/src/Controller/ExpenseController.php
> +        }
```suggestion
        if (!$group instanceof Group) {
            throw new HttpNotFoundException();
        }
        
        return $this->render('expense/list.html.twig', [
            'group' => $group,
        ]);
```

2023-04-20 08:55 UTC, HeleneAmouzou commented on apps/back/src/Controller/ExpenseController.php
> +        }
I have made this change in the previous PR :  [https://github.com/KnpLabs/QuiPayeQuoiHelene/pull/8](url)

2023-04-20 08:58 UTC, HeleneAmouzou commented on apps/back/src/Controller/GroupController.php
> +        $application->run($input, $output);
I saw it in the documentation, but I am going to follow your advice, thanks !

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/ExpenseController.php
> +    #[Route('/list/{groupName}', name: '_list')]
Tu peux également préciser la méthode utilisée pour tes routes ici. Les méthodes d'une API Rest (GET, POST, PUT, DELETE..). Cette route de liste est en GET tandis que ta route `add` est du POST.

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/ExpenseController.php
> +        string $groupName,
Potentiellement tu pourrais avoir plusieurs groupes avec le même nom non ? Il vaut mieux renvoyer l'`id` dans ton url et récupérer ton groupe avec un `$groupRepository->find($id)`. Ainsi tu n'auras pas de problème si jamais plusieurs groupes sont nommés pareil.

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/ExpenseController.php
> +        }
Tous les utilisateurs peuvent voir tous les groupes même s'ils n'en font pas parti ? Si seul un membre du groupe peut y accéder, il faudrait ajouter une sécurité ici pour vérifier que l'utilisateur connecté est bien membre et si ce n'est pas le cas, lui interdire l'accés à cette page. Tu peux récupérer l'utilisateur connecté assez facilement avec le bundle Security de Symfony : https://symfony.com/doc/current/security.html#fetching-the-user-object

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/GroupController.php
> +#[Route('/group', name: 'group')]
Idem, ce serait bien d'ajouter la méthode d'API

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/GroupController.php
> +    #[Route('/balance/{groupName}', name: '_balance')]
Idem, ce serait plus sécurisé de passer un `id` qu'un `name`

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/GroupController.php
> +    #[Route('/balance/{groupName}', name: '_balance')]
Est-ce que ça ne serait pas plus logique d'inverser l'ordre de tes entités dans l'url ? `/group/{groupId}/balance`
Car c'est la balance de ce groupe et non le groupe de cette balance non ?

2023-04-20 09:42 UTC, Manaaia commented on apps/back/src/Controller/GroupController.php
> +        $groupRepository = $em->getRepository(Group::class);
Vérifier également ici que l'utilisateur connecté a le droit d'accéder à cette page

2023-04-20 09:42 UTC, Manaaia commented on apps/back/templates/expense/list.html.twig
> +                <th>Nom Payé par</th>
Peut être séparer ces deux informations en deux colonnes dédiées pour plus de clarté ?

2023-04-20 13:52 UTC, qroques commented
Tu devrais baser cette branche sur `feat/list-exepense` ça réduira le nombre de fichiers "modifiés"

2023-04-21 14:25 UTC, HeleneAmouzou commented on apps/back/src/Controller/ExpenseController.php
> +        }
Merci, pour l'instant il n'y a pas d'authentification, mais je garde ça en tête pour plus tard :)

2023-04-21 14:39 UTC, HeleneAmouzou commented on apps/back/templates/expense/list.html.twig
> +                <th>Nom Payé par</th>
Le PO a validé cet affichage, j'ai juste fait un ajout dans `<td>{{ expense.name }} payé par {{ expense.payer.name }}</td>` pour que ce soit en effet un peu plus clair !

2023-04-24 08:26 UTC, Manaaia approved these changes

2023-04-24 09:32 UTC, qroques requested changes
Bonne idée d'avoir utiliser un service commun pour le calcul. 

Attention aux indentations (notamment dans le fichier BalanceService où c'est un peu freestyle et rend la review compliquée

2023-04-24 09:32 UTC, qroques commented on apps/back/src/Service/BalanceService.php
> +            }
Toute cette logique semble propre à la classe Expense.

Peut-être qu'une methode `getAmountPerParticipant` dans cette entité simplifierait les choses ici

2023-04-24 09:32 UTC, qroques commented on apps/back/src/Service/BalanceService.php
> +        }
Là encore, une partie de la logique pourrait être contenue à l'interieur de la classe Expense. 

Par exemple une methode `getBalance(User $user): int`
Qui renvoie donc la balance d'un utilisateur concernant une dépense. 
cette methode devrait prendre en compte 4 cas de figures 
- L'utilisateur est payeur et participant ;
- L'utiliasteur est payeur mais pas participant ;
- L'utilisateur n'est pas payeur mais participant ;
- L'utilisateur n'est ni payeur ni paritipant ;

Cette méthode renverait un nombre négatif dans le cas d'un utilisateur débiteur, positif sinon

2023-04-24 09:32 UTC, qroques commented on apps/back/templates/group/displayBalance.html.twig
> +        <a href="#">Retour</a>
Mettre un lien vers la page de liste par exemple

2023-04-25 08:22 UTC, HeleneAmouzou commented on apps/back/templates/group/displayBalance.html.twig
> +        <a href="#">Retour</a>
Il est prévu que ce lien retourne vers une page d'accueil qui n'a pas encore été créée

2023-04-25 09:31 UTC, qroques approved these changes

2023-04-25 11:46 UTC, KevinArtus requested changes

2023-04-25 11:46 UTC, KevinArtus commented on apps/back/src/Controller/GroupController.php
> +    }
```suggestion
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly BalanceService $balanceService
    ) {
    }
```

2023-04-25 11:46 UTC, KevinArtus commented on apps/back/src/Service/BalanceService.php
> +    public function __construct(public EntityManagerInterface $em)
1. This parameter should not be public.
2. You can use this instructions to set it
```suggestion
    public function __construct(private readonly EntityManagerInterface $em) 
    {
    }
```

2023-04-25 11:47 UTC, clementvtrd approved these changes

2023-04-27 08:42 UTC, merged